# Generated by Django 5.2 on 2025-08-27 11:16

import collects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="end_datetime",
            field=models.DateTimeField(
                help_text="Дата и время завершения сбора",
                validators=[collects.models.validate_future_date],
            ),
        ),
    ]
